
class InputColumn:
    STATE_FEATURES = "state_features"
    STATE_SEQUENCE_FEATURES = "state_sequence_features"
    NEXT_STATE_FEATURES = "next_state_features"
    NEXT_STATE_SEQUENCE_FEATURES = "next_state_sequence_features"
    ACTIONS = "actions"
    NEXT_ACTIONS = "next_actions"
    NOT_TERMINAL = "not_terminal"
    STEP = "step"
    TIME_DIFF = "time_diff"
    TIME_SINCE_FIRST = "time_since_first"
    MDP_ID = "mdp_id"
    SEQUENCE_NUMBER = "sequence_number"
    METRICS = "metrics"
    REWARD = "reward"
    ACTIONS_PROBABILITY = "actions_probability"
    SLATE_REWARD = "slate_reward"
    ITEM_REWARD = "item_reward"
